# Generated by Django 3.1.3 on 2020-11-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_auto_20201129_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemoryImage',
        ),
    ]
